### ISSUE TITLE
GUI Does not update while program is running

### ISSUE THREAD

**Issue by blueelvis** [certly/cscan#1]
After pressing the scan button, the GUI hangs. What we can do is create a separate thread and then just start everything in the separate thread. This resolves the main thread from seeming like it is hanged :0)

**Comment by MikeLierman** [comment]
Is this project dead and/or is this bug still an issue? Application crashes on my Win 10 machine. I can help solves some of these bugs.

**Comment by iangcarroll** [comment]
I haven't had time to work on it in a while, but yes, it is. It is probably crashing because of the incomplete [WinTrust code](https://github.com/certly/cscan/blob/master/CScan/WinTrustVerify.cs) for checking file signatures.

I'd be happy to answer any questions or merge any PRs that you have.

**Comment by MikeLierman** [comment]
I stole that Wintrust code for another project. Seriously spent weeks off
and on looking for a c# version. Shockingly little info out there about
getting hashes from Windows security catalog. Props to whoever made that.
You have it really close.

**Comment by MikeLierman** [comment]
Solved this issue. Can be closed once my PR is accepted.

**Comment by blueelvis** [comment]
Closing this since the PR has been merged. I want a welcome back surprise party from you @iangcarroll  @aurakal :package:
