### ISSUE TITLE
Doesn't report the full Windows 10 version

### ISSUE THREAD

**Issue by Aurakal** [certly/cscan#10]
Doesn't report the full Windows 10 version number. Stops at the main build, not the cumulative update. Would be a nice addition as it would allow us to spot systems that weren't updated.

CScan: Windows Version 10.0.10586.0
winver: Windows Version 10.0.10586.494

**Comment by Aurakal** [comment]
Possible lead. This key:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`
With this value:
`BuildLabEx`
Value (from my Windows 10 Pro non-Insider build):
`10586.494.amd64fre.th2_release_sec.160630-1736`
Basically we want the first 2 sets of numerical values, and drop everything after the second . (the . included). From there, we can just append it to the `CurrentVersion` data from the same key. However under Windows 10 that entry returns 6.3, so we could just swap it for 10.0 and append the rest.
`10.0.X.Y` (where X and Y are grabbed from the BuildLabEx entry)

I checked and that key exists in Windows 7 as well, so I suppose it also exists in Windows 8 and 8.1.

**Comment by Aurakal** [comment]
Under Windows 10, these two entries also exists:
`CurrentMajorVersionNumber` which is 10
`CurrentMinorVersionNumber` which is 0
Both are hex values, so we could query them instead and build the version number from these two values with the split from BuildLabEx.

**Comment by iangcarroll** [comment]
Fixed in 8411f69251208484bc87cb486e1516dacdc1537d by reading the `UBR` value from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`. I do not know if this works on Windows <10, but it will just not include it if it doesn't exist.

**Comment by iangcarroll** [comment]
On a side note, `BuildLabEx` doesn't show the revision number for me anymore, just `rs2-release`.
