### ISSUE TITLE
Few Important Proc: entries are missing path of the executable

### ISSUE THREAD

**Issue by blueelvis** [certly/cscan#20]
I ran CScan on my computer and got a log from that. Below is a snippet of the log file -

> Proc: (4) System
> Proc: (272) C:\Users\Blueelvis_RoXXX\AppData\Local\FluxSoftware\Flux\flux.exe 
> Proc: (288) C:\WINDOWS\System32\svchost.exe 
> Proc: (296) C:\WINDOWS\ImmersiveControlPanel\SystemSettings.exe 
> Proc: (332) smss 
> Proc: (348) C:\WINDOWS\system32\svchost.exe 
> Proc: (364) C:\WINDOWS\system32\svchost.exe  
> Proc: (448) csrss 
> Proc: (464) C:\Users\Blueelvis_RoXXX\AppData\Local\Google\Chrome\Application\chrome.exe 
> Proc: (524) wininit 
> Proc: (536) csrss
> Proc: (612) C:\WINDOWS\system32\winlogon.exe 
> Proc: (696) C:\Program Files (x86)\Common Files\Microsoft Shared\VsHub\1.0.0.0\Microsoft.VsHub.Server.HttpHost.exe 
> Proc: (708) services

See? The important executables don't have their path listed. This is important while detecting malware. What do you think?
- [ ] Fix the above paths for the executables
- [ ] Replace normal SPACE with TAB to correct formatting.

**Comment by Aurakal** [comment]
Is it because CScan isn't ran with Admin Rights?

**Comment by blueelvis** [comment]
@Aurakal - It is running with Administrator Rights. There are formatting issues as well. The output lines are not properly spaced (Need a TAB space instead).

Changed the bug description as well.

**Comment by iangcarroll** [comment]
There is, if I remember correctly, a new API for retrieving the process path which will not throw this error on system processes.

**Comment by iangcarroll** [comment]
Relevant: http://stackoverflow.com/questions/3399819/access-denied-while-getting-process-path/3654195#3654195

**Comment by iangcarroll** [comment]
I believe this behavior is documented, at least [somewhat](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684320(v=vs.85).aspx):
>  If the specified process is the System Process (0x00000000), the function fails and the last error code is ERROR_INVALID_PARAMETER. If the specified process is the Idle process or one of the CSRSS processes, this function fails and the last error code is ERROR_ACCESS_DENIED because their access restrictions prevent user-level code from opening them.

Since all of the processes this fails on have Light WinTcb/Antimalware protection, I don't think hiding these processes will become an issue.

We might be able to call Process Hacker's kernel extension at some point, but it's probably overkill.
