### ISSUE TITLE
Adjust the Prg: scan

### ISSUE THREAD

**Issue by Aurakal** [certly/cscan#29]
The Prg: scan is missing the publisher name. Also, might be worth adding a small checkbox option to list the UninstallString value as it can be useful sometimes. Also, maybe list if the program is installed on the system (HKLM) or the profile (HKCU/HKU).

Another side idea: add the "Installed on" date.

https://stackoverflow.com/questions/18679441/where-does-add-remove-programs-pull-data-for-the-installed-on-column

**Comment by iangcarroll** [comment]
Done:
```
Prg: [HKLM] (Oracle Corporation) Java 8 Update 131 (64-bit) 
Prg: [HKLM] (Oracle Corporation) Java Auto Updater [b](Hidden)[/b] 
Prg: [HKCU] (JetBrains s.r.o.) JetBrains dotPeek 2016.2.2 
```

I actually forgot to search HKCU for these entries, but that's also been fixed.
